### ISSUE TITLE
Install error: Operation could not be supported

### ISSUE THREAD

**Issue by happyismoho** [Iristyle/PerfTap#15]
Can anyone shed some light on the following error when I install Perftap?

OS: Windows 2012 R2, Node in a MS fail over cluster

System.IO.FileLoadException: Could not load file or assembly 'file:///c:\PerfTap
\PerfTap.WindowsServiceHost.exe' or one of its dependencies. Operation is not supported

**Comment by cemsbr** [comment]
Workaround: click with the right mouse button on the service exe file and then in the "Unblock" button. After that, install the service with installutil.exe as in the ps1 script.
